import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  splashMain: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  Splashtxt: {
    color: 'white',
    fontSize: 25,
  },
  DashboardParantView: {
    flex: 1,
  },
  DB_Header: {
    backgroundColor: 'blue',
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  DB_HeaderText: {color: 'white', fontSize: 20},
  DBtextField: {
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 20,
    height: 50,
    elevation: 5,
    backgroundColor: 'white',
  },
  DB_inputField: {color: 'black', fontSize: 16, marginLeft: 10, flex: 1},
  DB_DOB: {
    marginLeft: 20,
    marginVertical: 10,
    color: 'black',
    fontSize: 16,
  },
  DB_btn_parent: {
    marginVertical: 50,
    marginHorizontal: 20,
    flexDirection: 'row',
  },
  DB_add_item: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginRight: 5,
    borderRadius: 20,
    backgroundColor: 'white',
    height: 60,
    elevation: 5,
  },
  DB_go_list: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginLeft: 5,
    borderRadius: 20,
    backgroundColor: 'white',
    height: 60,
    elevation: 5,
  },
  DB_btn_txt_style: {color: 'blue', fontWeight: 'bold', fontSize: 20},
  FlatListParentView: {
    marginVertical: 10,
    marginHorizontal: 20,
    backgroundColor: 'white',
    borderRadius: 5,
    elevation: 5,
  },
  FlatlistInnerView: {marginVertical: 10, marginHorizontal: 10},
  FlatlistTxt: {color: 'black', fontWeight: 'bold', fontSize: 16},
  SearchParantView: {
    backgroundColor: 'white',
    borderRadius: 30,
    height: 48,
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 10,
  },
  Search_img: {
    height: 18,
    width: 18,
    resizeMode: 'contain',
    marginRight: 8,
    marginLeft: 19,
  },
  Search_txt: {color: 'black', fontSize: 16, flex: 1},
  errMsgStyle: {color: 'red'},
});
